version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
    networks:
      - flaskr-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db:5432/flaskrdb
      - REDIS_HOST=redis
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SECRET_NAME=${SECRET_NAME}
    volumes:
      - ./backend:/flaskr
      - ./logs:/flaskr/logs
    networks:
      - flaskr-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flaskr-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - flaskr-network

volumes:
  postgres_data:

networks:
  flaskr-network:
    driver: bridge