version: '3'

services:
 frontend:
   build: 
     context: ./frontend
     dockerfile: Dockerfile
   ports:
     - "3000:80"
   depends_on:
     - backend

 backend:
   build: 
     context: ./backend
     dockerfile: Dockerfile
   environment:
     - FLASK_ENV=development
     - SQLALCHEMY_DATABASE_URI=postgresql://username:password@db:5432/mydatabase
   ports:
     - "5000:5000"
   depends_on:
     - db
   volumes:
     - ./logs:/flaskr/logs

 db:
   image: postgres:13
   environment:
     - POSTGRES_USER=username
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=mydatabase
   volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: