version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"   # Redirect HTTP to HTTPS
      - "443:443" # HTTPS port
    depends_on:
      - backend
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - ACM_CERTIFICATE_ARN=${ACM_CERTIFICATE_ARN}
    networks:
      - flaskr-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    depends_on:
      - db
      - redis
    environment:
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@db:5432/flaskrdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - SECRET_NAME=${SECRET_NAME}
    volumes:
      - ./logs:/flaskr/logs
    networks:
      - flaskr-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flaskrdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flaskr-network

  redis:
    image: redis:6-alpine
    networks:
      - flaskr-network

volumes:
  postgres_data:

networks:
  flaskr-network:
    driver: bridge